### ISSUE TITLE
Practica 5

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-NoeliaGlez#2]
[Practica5_Boton_Personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-NoeliaGlez/files/8867174/Practica5_Boton_Personalizado.pdf)

**Comment by Litzy-lopez4** [comment]
17.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado
